news:
  - date: "2017/03/22（水）"
    title: "オープンキャンペーン！<br>無料会員登録で今すぐ使える 1,000円分のポイント進呈！"
    link: "https://c07.future-shop.jp/fs/softtennis/MemberEntryEdit.html"
  - date: "2017/03/22（水）"
    title: "ブログ、Twitter、Facebook やってます。見に来て下さい"
    link: "http://lafino-softtennis.officialblog.jp/"
  - date: "2017/03/22（水）"
    title: "ソフトテニスショップ LAFINO オープン！"
    link: "https://c07.future-shop.jp/fs/softtennis/MemberEntryEdit.html"

pickup:
  text: "オープンキャンペーン！<br>無料会員登録で<br>今すぐ使える 1,000円 分のポイント進呈！"
  button: "今すぐ登録"
  link: "https://c07.future-shop.jp/fs/softtennis/MemberEntryEdit.html"

new_products:
  - name: "YONEX ラケット<br>F-LASER 7S"
    img: "http://www.softtennis-lafino.jp/shop/item/softtennis/picture/goods/7_1.jpg"
    link: "http://www.softtennis-lafino.jp/fs/softtennis/F-LASER/FLR7S-001"
    discount_price: "19,008"
    fixed_price: "21,384"
  - name: "MIZUNO シューズ<br>WAVE EXCEED OC"
    img: "http://www.softtennis-lafino.jp/shop/item/softtennis/picture/goods/40_1.jpg"
    link: "http://www.softtennis-lafino.jp/fs/softtennis/soft-shoes/61GB171301"
    discount_price: "12,441 "
    fixed_price: "13,824 "
  - name: "YONEX ガット<br>V-ACCEL 1.25mm "
    img: "http://www.softtennis-lafino.jp/shop/item/softtennis/picture/goods/9_1.jpg"
    link: "http://www.softtennis-lafino.jp/fs/softtennis/soft-gut/SGVA"
    discount_price: "1,814"
    fixed_price: "2,268"
  - name: "SRIXON テニスボール<br>公認球 12球入"
    img: "http://www.softtennis-lafino.jp/shop/item/softtennis/picture/goods/79_1.jpg"
    link: "http://www.softtennis-lafino.jp/fs/softtennis/soft-ball/STBD2DOZ"
    discount_price: "3,628 "
    fixed_price: "4,536"
  - name: "MIZUNO ラケット<br>Deep Impact Z-FORWARD"
    img: "http://www.softtennis-lafino.jp/shop/item/softtennis/picture/goods/89_1.jpg"
    link: "http://www.softtennis-lafino.jp/fs/softtennis/mizuno-racket/63JTN68001"
    discount_price: "22,356"
    fixed_price: "24,840"